
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import ProviderWrapper from "@/redux/providerWrapper";
import { useSession } from "next-auth/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TODO WITH BACKEND",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data: session } = useSession();
  return (
    <html lang="en">
      <body className={inter.className}>
      <ProviderWrapper >  {children}</ProviderWrapper>

      </body>
    </html>
  );
}
