import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import ProviderWrapper from "@/redux/provider_wrapper";
import SessionWrapper from "./api/auth/session_wrapper";
import { useSession } from "next-auth/react";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TODO WITH BACKEND",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderWrapper>
    
          <SessionWrapper session={null} > {children}</SessionWrapper>
        </ProviderWrapper>
      </body>
    </html>
  );
}
